"""add token columns to agent_decisions

Revision ID: 0235ff20694c
Revises: 0001
Create Date: 2026-04-16 12:34:16.464175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0235ff20694c'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('admin_feedback_embedding_idx'), table_name='admin_feedback', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.add_column('agent_decisions', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('agent_decisions', sa.Column('output_tokens', sa.Integer(), nullable=True))
    op.add_column('agent_decisions', sa.Column('cache_read_tokens', sa.Integer(), nullable=True))
    op.add_column('agent_decisions', sa.Column('cache_creation_tokens', sa.Integer(), nullable=True))
    op.drop_index(op.f('messages_embedding_idx'), table_name='messages', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('messages_embedding_idx'), 'messages', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_column('agent_decisions', 'cache_creation_tokens')
    op.drop_column('agent_decisions', 'cache_read_tokens')
    op.drop_column('agent_decisions', 'output_tokens')
    op.drop_column('agent_decisions', 'input_tokens')
    op.create_index(op.f('admin_feedback_embedding_idx'), 'admin_feedback', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
