"""add_briefings_table

Revision ID: 6986d454bbf2
Revises: a0ca1df0dc7e
Create Date: 2026-04-21 21:23:38.403887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6986d454bbf2'
down_revision: Union[str, Sequence[str], None] = 'a0ca1df0dc7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('briefings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('briefing_text', sa.Text(), nullable=False),
    sa.Column('threads_covered', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('briefings')
    # ### end Alembic commands ###
